export const vendorsDetailsData = [
    {
      "vendorName": "Alpha Technologies",
      "vendorDesc": "A leading provider of IT services and cybersecurity solutions.",
      "vendorCountry": "USA",
      "vendorCity": "New York",
      "vendorOrg": "Alpha Group",
      "vendorDateOfBreach": "2023-05-10",
      "vendorBreachDetails": "Unauthorized access to user accounts, exposing sensitive data.",
      "vendorIdentifyScore": 75,
      "vendorProtectScore": 80,
      "vendorDetectScore": 77,
      "vendorRespondScore": 74,
      "vendorRecoverScore": 85,
      "dns": "alpha-tech.com",
      "averageTotalRiskScore": 78,
      "vendorVulnerabilities": ["SQL Injection", "Cross-Site Scripting (XSS)", "Weak Password Policies"],
      "vendorReferenceLinks": ["https://alpha-tech.com/breach-report", "https://cybernews.com/alpha-breach"],
      "companyId": "COMP001"
    },
    {
      "vendorName": "Beta Industries",
      "vendorDesc": "Manufacturing giant specializing in electronics and smart devices.",
      "vendorCountry": "Germany",
      "vendorCity": "Berlin",
      "vendorOrg": "Beta Global",
      "vendorDateOfBreach": "2022-11-15",
      "vendorBreachDetails": "Data breach involving compromised employee and customer information.",
      "vendorIdentifyScore": 70,
      "vendorProtectScore": 68,
      "vendorDetectScore": 66,
      "vendorRespondScore": 65,
      "vendorRecoverScore": 72,
      "dns": "beta-industries.de",
      "averageTotalRiskScore": 65,
      "vendorVulnerabilities": ["Phishing Attacks", "Malware Infection", "Insider Threats"],
      "vendorReferenceLinks": ["https://beta-industries.de/security-incident", "https://cybernews.com/beta-breach"],
      "companyId": "COMP002"
    },
    {
      "vendorName": "Gamma Solutions",
      "vendorDesc": "A software development company focused on cloud-based solutions.",
      "vendorCountry": "India",
      "vendorCity": "Bangalore",
      "vendorOrg": "Gamma Group",
      "vendorDateOfBreach": "2024-03-22",
      "vendorBreachDetails": "Hackers exploited a vulnerability in the cloud infrastructure.",
      "vendorIdentifyScore": 80,
      "vendorProtectScore": 85,
      "vendorDetectScore": 83,
      "vendorRespondScore": 82,
      "vendorRecoverScore": 78,
      "dns": "gamma-solutions.in",
      "averageTotalRiskScore": 82,
      "vendorVulnerabilities": ["Cloud Misconfiguration", "Insecure APIs", "Data Leakage"],
      "vendorReferenceLinks": ["https://gamma-solutions.in/breach-details", "https://cybernews.com/gamma-breach"],
      "companyId": "COMP003"
    },
    {
      "vendorName": "Delta Corp",
      "vendorDesc": "Global leader in consumer electronics and home appliances.",
      "vendorCountry": "South Korea",
      "vendorCity": "Seoul",
      "vendorOrg": "Delta Holdings",
      "vendorDateOfBreach": "2023-08-19",
      "vendorBreachDetails": "Customer data was exposed through a third-party vendor.",
      "vendorIdentifyScore": 60,
      "vendorProtectScore": 55,
      "vendorDetectScore": 57,
      "vendorRespondScore": 56,
      "vendorRecoverScore": 62,
      "dns": "delta-corp.kr",
      "averageTotalRiskScore": 55,
      "vendorVulnerabilities": ["Third-Party Risk", "Weak Encryption", "Data Exposure"],
      "vendorReferenceLinks": ["https://delta-corp.kr/security-incident", "https://cybernews.com/delta-breach"],
      "companyId": "COMP004"
    },
    {
      "vendorName": "Epsilon Services",
      "vendorDesc": "Financial services firm specializing in investment banking.",
      "vendorCountry": "UK",
      "vendorCity": "London",
      "vendorOrg": "Epsilon Group",
      "vendorDateOfBreach": "2021-12-29",
      "vendorBreachDetails": "Massive data breach affecting millions of customers worldwide.",
      "vendorIdentifyScore": 90,
      "vendorProtectScore": 88,
      "vendorDetectScore": 85,
      "vendorRespondScore": 87,
      "vendorRecoverScore": 89,
      "dns": "epsilon-services.co.uk",
      "averageTotalRiskScore": 90,
      "vendorVulnerabilities": ["Phishing Attacks", "Data Exfiltration", "Zero-Day Exploits"],
      "vendorReferenceLinks": ["https://epsilon-services.co.uk/breach-report", "https://cybernews.com/epsilon-breach"],
      "companyId": "COMP005"
    },
    {
      "vendorName": "Zeta Enterprises",
      "vendorDesc": "Leading e-commerce platform with a global presence.",
      "vendorCountry": "China",
      "vendorCity": "Shanghai",
      "vendorOrg": "Zeta Group",
      "vendorDateOfBreach": "2023-04-14",
      "vendorBreachDetails": "Payment information was compromised during a cyber attack.",
      "vendorIdentifyScore": 78,
      "vendorProtectScore": 75,
      "vendorDetectScore": 70,
      "vendorRespondScore": 73,
      "vendorRecoverScore": 77,
      "dns": "zeta-enterprises.cn",
      "averageTotalRiskScore": 72,
      "vendorVulnerabilities": ["Ransomware", "Payment Card Fraud", "Supply Chain Attack"],
      "vendorReferenceLinks": ["https://zeta-enterprises.cn/breach-details", "https://cybernews.com/zeta-breach"],
      "companyId": "COMP006"
    },
    {
      "vendorName": "Eta Tech",
      "vendorDesc": "An innovative tech company focusing on AI and machine learning.",
      "vendorCountry": "Canada",
      "vendorCity": "Toronto",
      "vendorOrg": "Eta Technologies",
      "vendorDateOfBreach": "2023-02-28",
      "vendorBreachDetails": "Sensitive data was leaked due to an insider threat.",
      "vendorIdentifyScore": 65,
      "vendorProtectScore": 63,
      "vendorDetectScore": 60,
      "vendorRespondScore": 62,
      "vendorRecoverScore": 66,
      "dns": "eta-tech.ca",
      "averageTotalRiskScore": 68,
      "vendorVulnerabilities": ["Insider Threat", "Data Leakage", "Phishing"],
      "vendorReferenceLinks": ["https://eta-tech.ca/security-incident", "https://cybernews.com/eta-breach"],
      "companyId": "COMP007"
    },
    {
      "vendorName": "Theta Innovations",
      "vendorDesc": "A startup specializing in blockchain and decentralized technologies.",
      "vendorCountry": "USA",
      "vendorCity": "San Francisco",
      "vendorOrg": "Theta Group",
      "vendorDateOfBreach": "2022-10-01",
      "vendorBreachDetails": "Hackers exploited a vulnerability in the smart contract system.",
      "vendorIdentifyScore": 75,
      "vendorProtectScore": 78,
      "vendorDetectScore": 76,
      "vendorRespondScore": 74,
      "vendorRecoverScore": 79,
      "dns": "theta-innovations.com",
      "averageTotalRiskScore": 77,
      "vendorVulnerabilities": ["Smart Contract Vulnerabilities", "DDoS Attacks", "Phishing"],
      "vendorReferenceLinks": ["https://theta-innovations.com/breach-report", "https://cybernews.com/theta-breach"],
      "companyId": "COMP008"
    },
    {
      "vendorName": "Iota Solutions",
      "vendorDesc": "Provider of IoT solutions for smart homes and cities.",
      "vendorCountry": "Japan",
      "vendorCity": "Tokyo",
      "vendorOrg": "Iota Corporation",
      "vendorDateOfBreach": "2024-01-16",
      "vendorBreachDetails": "IoT devices were compromised, leading to a significant data breach.",
      "vendorIdentifyScore": 68,
      "vendorProtectScore": 65,
      "vendorDetectScore": 64,
      "vendorRespondScore": 67,
      "vendorRecoverScore": 66,
      "dns": "iota-solutions.jp",
      "averageTotalRiskScore": 62,
      "vendorVulnerabilities": ["IoT Device Vulnerabilities", "Insecure Networks", "Data Exposure"],
      "vendorReferenceLinks": ["https://iota-solutions.jp/breach-details", "https://cybernews.com/iota-breach"],
      "companyId": "COMP009"
    },
    {
      "vendorName": "Kappa Systems",
      "vendorDesc": "Specializes in enterprise software solutions and IT consulting.",
      "vendorCountry": "Australia",
      "vendorCity": "Sydney",
      "vendorOrg": "Kappa Technologies",
      "vendorDateOfBreach": "2023-11-21",
      "vendorBreachDetails": "Unauthorized access to client data through a phishing attack.",
      "vendorIdentifyScore": 75,
      "vendorProtectScore": 79,
      "vendorDetectScore": 77,
      "vendorRespondScore": 73,
      "vendorRecoverScore": 80,
      "dns": "kappa-systems.au",
      "averageTotalRiskScore": 79,
      "vendorVulnerabilities": ["Phishing", "Unauthorized Access", "Insufficient Network Security"],
      "vendorReferenceLinks": ["https://kappa-systems.au/security-incident", "https://cybernews.com/kappa-breach"],
      "companyId": "COMP010"
    },
    {
      "vendorName": "Lambda Networks",
      "vendorDesc": "Telecommunications company providing internet and mobile services.",
      "vendorCountry": "USA",
      "vendorCity": "Los Angeles",
      "vendorOrg": "Lambda Group",
      "vendorDateOfBreach": "2024-06-11",
      "vendorBreachDetails": "A breach in the network infrastructure exposed customer data.",
      "vendorIdentifyScore": 85,
      "vendorProtectScore": 82,
      "vendorDetectScore": 80,
      "vendorRespondScore": 83,
      "vendorRecoverScore": 86,
      "dns": "lambda-networks.com",
      "averageTotalRiskScore": 81,
      "vendorVulnerabilities": ["Network Vulnerabilities", "Data Exposure", "Malware"],
      "vendorReferenceLinks": ["https://lambda-networks.com/breach-details", "https://cybernews.com/lambda-breach"],
      "companyId": "COMP011"
    },
    {
      "vendorName": "Mu Enterprises",
      "vendorDesc": "Retail company with a wide range of products, both online and in-store.",
      "vendorCountry": "Brazil",
      "vendorCity": "São Paulo",
      "vendorOrg": "Mu Group",
      "vendorDateOfBreach": "2023-07-23",
      "vendorBreachDetails": "Payment processing system was compromised, leading to a data breach.",
      "vendorIdentifyScore": 70,
      "vendorProtectScore": 72,
      "vendorDetectScore": 73,
      "vendorRespondScore": 75,
      "vendorRecoverScore": 80,
      "dns": "mu-enterprises.br",
      "averageTotalRiskScore": 75,
      "vendorVulnerabilities": ["Payment System Vulnerabilities", "SQL Injection", "Phishing"],
      "vendorReferenceLinks": ["https://mu-enterprises.br/breach-details", "https://cybernews.com/mu-breach"],
      "companyId": "COMP012"
    },
    {
      "vendorName": "Nu Technologies",
      "vendorDesc": "Tech company specializing in mobile applications and services.",
      "vendorCountry": "France",
      "vendorCity": "Paris",
      "vendorOrg": "Nu Group",
      "vendorDateOfBreach": "2022-05-30",
      "vendorBreachDetails": "Mobile app was compromised, leading to the exposure of user data.",
      "vendorIdentifyScore": 83,
      "vendorProtectScore": 85,
      "vendorDetectScore": 82,
      "vendorRespondScore": 81,
      "vendorRecoverScore": 84,
      "dns": "nu-technologies.fr",
      "averageTotalRiskScore": 83,
      "vendorVulnerabilities": ["Mobile App Vulnerabilities", "Insecure Data Storage", "Phishing"],
      "vendorReferenceLinks": ["https://nu-technologies.fr/breach-report", "https://cybernews.com/nu-breach"],
      "companyId": "COMP013"
    },
    {
      "vendorName": "Xi Cybersecurity",
      "vendorDesc": "Cybersecurity firm providing advanced security solutions.",
      "vendorCountry": "USA",
      "vendorCity": "Washington, D.C.",
      "vendorOrg": "Xi Group",
      "vendorDateOfBreach": "2024-02-08",
      "vendorBreachDetails": "Zero-day exploit led to unauthorized access to sensitive information.",
      "vendorIdentifyScore": 90,
      "vendorProtectScore": 87,
      "vendorDetectScore": 85,
      "vendorRespondScore": 88,
      "vendorRecoverScore": 84,
      "dns": "xi-cybersecurity.com",
      "averageTotalRiskScore": 87,
      "vendorVulnerabilities": ["Zero-Day Exploits", "Data Exfiltration", "Insider Threats"],
      "vendorReferenceLinks": ["https://xi-cybersecurity.com/breach-report", "https://cybernews.com/xi-breach"],
      "companyId": "COMP014"
    },
    {
      "vendorName": "Omicron Corp",
      "vendorDesc": "A multinational corporation involved in manufacturing and logistics.",
      "vendorCountry": "USA",
      "vendorCity": "Chicago",
      "vendorOrg": "Omicron Group",
      "vendorDateOfBreach": "2023-09-10",
      "vendorBreachDetails": "Internal system breach exposed sensitive customer information.",
      "vendorIdentifyScore": 70,
      "vendorProtectScore": 68,
      "vendorDetectScore": 69,
      "vendorRespondScore": 65,
      "vendorRecoverScore": 67,
      "dns": "omicron-corp.com",
      "averageTotalRiskScore": 69,
      "vendorVulnerabilities": ["Insider Threat", "Weak Access Controls", "Social Engineering"],
      "vendorReferenceLinks": ["https://omicron-corp.com/security-incident", "https://cybernews.com/omicron-breach"],
      "companyId": "COMP015"
    },
    {
      "vendorName": "Pi Software",
      "vendorDesc": "Software development firm specializing in enterprise solutions.",
      "vendorCountry": "USA",
      "vendorCity": "Austin",
      "vendorOrg": "Pi Group",
      "vendorDateOfBreach": "2022-01-05",
      "vendorBreachDetails": "A breach in the software update system led to unauthorized access.",
      "vendorIdentifyScore": 73,
      "vendorProtectScore": 70,
      "vendorDetectScore": 68,
      "vendorRespondScore": 72,
      "vendorRecoverScore": 75,
      "dns": "pi-software.com",
      "averageTotalRiskScore": 71,
      "vendorVulnerabilities": ["Software Update Vulnerabilities", "Malware", "Phishing"],
      "vendorReferenceLinks": ["https://pi-software.com/breach-details", "https://cybernews.com/pi-breach"],
      "companyId": "COMP016"
    },
    {
      "vendorName": "Rho Technologies",
      "vendorDesc": "A global technology firm specializing in AI and big data.",
      "vendorCountry": "China",
      "vendorCity": "Beijing",
      "vendorOrg": "Rho Group",
      "vendorDateOfBreach": "2023-12-17",
      "vendorBreachDetails": "AI system was compromised, leading to a major data breach.",
      "vendorIdentifyScore": 87,
      "vendorProtectScore": 89,
      "vendorDetectScore": 85,
      "vendorRespondScore": 86,
      "vendorRecoverScore": 88,
      "dns": "rho-technologies.cn",
      "averageTotalRiskScore": 85,
      "vendorVulnerabilities": ["AI System Vulnerabilities", "Data Exfiltration", "Insider Threat"],
      "vendorReferenceLinks": ["https://rho-technologies.cn/breach-details", "https://cybernews.com/rho-breach"],
      "companyId": "COMP017"
    },
    {
      "vendorName": "Sigma Enterprises",
      "vendorDesc": "Provider of IT and software services for various industries.",
      "vendorCountry": "Italy",
      "vendorCity": "Rome",
      "vendorOrg": "Sigma Group",
      "vendorDateOfBreach": "2024-04-07",
      "vendorBreachDetails": "A ransomware attack led to the encryption of sensitive data.",
      "vendorIdentifyScore": 72,
      "vendorProtectScore": 75,
      "vendorDetectScore": 74,
      "vendorRespondScore": 70,
      "vendorRecoverScore": 76,
      "dns": "sigma-enterprises.it",
      "averageTotalRiskScore": 73,
      "vendorVulnerabilities": ["Ransomware", "Phishing", "Weak Access Controls"],
      "vendorReferenceLinks": ["https://sigma-enterprises.it/security-incident", "https://cybernews.com/sigma-breach"],
      "companyId": "COMP018"
    },
    {
      "vendorName": "Tau Systems",
      "vendorDesc": "Technology company providing enterprise software and cloud services.",
      "vendorCountry": "USA",
      "vendorCity": "San Francisco",
      "vendorOrg": "Tau Group",
      "vendorDateOfBreach": "2023-03-31",
      "vendorBreachDetails": "Cloud storage misconfiguration exposed sensitive customer data.",
      "vendorIdentifyScore": 74,
      "vendorProtectScore": 77,
      "vendorDetectScore": 75,
      "vendorRespondScore": 73,
      "vendorRecoverScore": 79,
      "dns": "tau-systems.com",
      "averageTotalRiskScore": 76,
      "vendorVulnerabilities": ["Cloud Storage Misconfiguration", "Insecure APIs", "Phishing"],
      "vendorReferenceLinks": ["https://tau-systems.com/breach-details", "https://cybernews.com/tau-breach"],
      "companyId": "COMP019"
    },
    {
      "vendorName": "Upsilon Networks",
      "vendorDesc": "Global telecommunications company with a focus on 5G technology.",
      "vendorCountry": "South Korea",
      "vendorCity": "Seoul",
      "vendorOrg": "Upsilon Group",
      "vendorDateOfBreach": "2022-09-18",
      "vendorBreachDetails": "Unauthorized access to customer data through a network vulnerability.",
      "vendorIdentifyScore": 82,
      "vendorProtectScore": 84,
      "vendorDetectScore": 80,
      "vendorRespondScore": 83,
      "vendorRecoverScore": 85,
      "dns": "upsilon-networks.kr",
      "averageTotalRiskScore": 84,
      "vendorVulnerabilities": ["Network Vulnerabilities", "DDoS Attacks", "Phishing"],
      "vendorReferenceLinks": ["https://upsilon-networks.kr/security-incident", "https://cybernews.com/upsilon-breach"],
      "companyId": "COMP020"
    }
  ]
  