import { useState } from "react";

export default function Accordion(props) {
    const [allSectors, setAllSectors] = useState([
        { "sectorId": 0, "sectorName": "All" },
        { "sectorId": 1, "sectorName": "Agriculture" },
        { "sectorId": 2, "sectorName": "Aerospace" },
        { "sectorId": 3, "sectorName": "Banking" },
        { "sectorId": 4, "sectorName": "Chemicals" },
        { "sectorId": 5, "sectorName": "Construction" },
        { "sectorId": 6, "sectorName": "Consumer Goods" },
        { "sectorId": 7, "sectorName": "Defense" },
        { "sectorId": 8, "sectorName": "Education" },
        { "sectorId": 9, "sectorName": "Energy" },
        { "sectorId": 10, "sectorName": "Entertainment" },
        { "sectorId": 11, "sectorName": "Financial Services" },
        { "sectorId": 12, "sectorName": "Food & Beverage" },
        { "sectorId": 13, "sectorName": "Government" },
        { "sectorId": 14, "sectorName": "Healthcare" },
        { "sectorId": 15, "sectorName": "Hospitality" },
        { "sectorId": 16, "sectorName": "Information Technology" },
        { "sectorId": 17, "sectorName": "Insurance" },
        { "sectorId": 18, "sectorName": "Legal" },
        { "sectorId": 19, "sectorName": "Logistics" },
        { "sectorId": 20, "sectorName": "Manufacturing" },
        { "sectorId": 21, "sectorName": "Marine" },
        { "sectorId": 22, "sectorName": "Media" },
        { "sectorId": 23, "sectorName": "Mining" },
        { "sectorId": 24, "sectorName": "Non-Profit" },
        { "sectorId": 25, "sectorName": "Oil & Gas" },
        { "sectorId": 26, "sectorName": "Pharmaceuticals" },
        { "sectorId": 27, "sectorName": "Professional Services" },
        { "sectorId": 28, "sectorName": "Public Sector" },
        { "sectorId": 29, "sectorName": "Real Estate" },
        { "sectorId": 30, "sectorName": "Retail" },
        { "sectorId": 31, "sectorName": "Shipping" },
        { "sectorId": 32, "sectorName": "Telecommunications" },
        { "sectorId": 33, "sectorName": "Textiles" },
        { "sectorId": 34, "sectorName": "Tourism" },
        { "sectorId": 35, "sectorName": "Transportation" },
        { "sectorId": 36, "sectorName": "Utilities" },
        { "sectorId": 37, "sectorName": "Waste Management" },
        { "sectorId": 38, "sectorName": "Water" },
        { "sectorId": 39, "sectorName": "Automotive" },
        { "sectorId": 40, "sectorName": "Aviation" },
        { "sectorId": 41, "sectorName": "Biotechnology" },
        { "sectorId": 42, "sectorName": "Cement" },
        { "sectorId": 43, "sectorName": "Commercial Banking" },
        { "sectorId": 44, "sectorName": "Cybersecurity" },
        { "sectorId": 45, "sectorName": "Electronics" },
        { "sectorId": 46, "sectorName": "Forestry" },
        { "sectorId": 47, "sectorName": "Gambling" },
        { "sectorId": 48, "sectorName": "Glass" },
        { "sectorId": 49, "sectorName": "Insurance Brokers" },
        { "sectorId": 50, "sectorName": "Investment Banking" },
        { "sectorId": 51, "sectorName": "Metals" },
        { "sectorId": 52, "sectorName": "Pension Funds" },
        { "sectorId": 53, "sectorName": "Petroleum" },
        { "sectorId": 54, "sectorName": "Railways" },
        { "sectorId": 55, "sectorName": "Recycling" },
        { "sectorId": 56, "sectorName": "Semiconductors" },
        { "sectorId": 57, "sectorName": "Software" },
        { "sectorId": 58, "sectorName": "Venture Capital" }
      ]
      )
      const [allCountries, setAllCountries] = useState([
        { "countryId": 0, "countryName": "All" },
        { "countryId": 1, "countryName": "Afghanistan" },
        { "countryId": 2, "countryName": "Albania" },
        { "countryId": 3, "countryName": "Algeria" },
        { "countryId": 4, "countryName": "Andorra" },
        { "countryId": 5, "countryName": "Angola" },
        { "countryId": 6, "countryName": "Antigua and Barbuda" },
        { "countryId": 7, "countryName": "Argentina" },
        { "countryId": 8, "countryName": "Armenia" },
        { "countryId": 9, "countryName": "Australia" },
        { "countryId": 10, "countryName": "Austria" },
        { "countryId": 11, "countryName": "Azerbaijan" },
        { "countryId": 12, "countryName": "Bahamas" },
        { "countryId": 13, "countryName": "Bahrain" },
        { "countryId": 14, "countryName": "Bangladesh" },
        { "countryId": 15, "countryName": "Barbados" },
        { "countryId": 16, "countryName": "Belarus" },
        { "countryId": 17, "countryName": "Belgium" },
        { "countryId": 18, "countryName": "Belize" },
        { "countryId": 19, "countryName": "Benin" },
        { "countryId": 20, "countryName": "Bhutan" },
        { "countryId": 21, "countryName": "Bolivia" },
        { "countryId": 22, "countryName": "Bosnia and Herzegovina" },
        { "countryId": 23, "countryName": "Botswana" },
        { "countryId": 24, "countryName": "Brazil" },
        { "countryId": 25, "countryName": "Brunei" },
        { "countryId": 26, "countryName": "Bulgaria" },
        { "countryId": 27, "countryName": "Burkina Faso" },
        { "countryId": 28, "countryName": "Burundi" },
        { "countryId": 29, "countryName": "Cabo Verde" },
        { "countryId": 30, "countryName": "Cambodia" },
        { "countryId": 31, "countryName": "Cameroon" },
        { "countryId": 32, "countryName": "Canada" },
        { "countryId": 33, "countryName": "Central African Republic" },
        { "countryId": 34, "countryName": "Chad" },
        { "countryId": 35, "countryName": "Chile" },
        { "countryId": 36, "countryName": "China" },
        { "countryId": 37, "countryName": "Colombia" },
        { "countryId": 38, "countryName": "Comoros" },
        { "countryId": 39, "countryName": "Congo, Democratic Republic of the" },
        { "countryId": 40, "countryName": "Congo, Republic of the" },
        { "countryId": 41, "countryName": "Costa Rica" },
        { "countryId": 42, "countryName": "Croatia" },
        { "countryId": 43, "countryName": "Cuba" },
        { "countryId": 44, "countryName": "Cyprus" },
        { "countryId": 45, "countryName": "Czech Republic" },
        { "countryId": 46, "countryName": "Denmark" },
        { "countryId": 47, "countryName": "Djibouti" },
        { "countryId": 48, "countryName": "Dominica" },
        { "countryId": 49, "countryName": "Dominican Republic" },
        { "countryId": 50, "countryName": "Ecuador" },
        { "countryId": 51, "countryName": "Egypt" },
        { "countryId": 52, "countryName": "El Salvador" },
        { "countryId": 53, "countryName": "Equatorial Guinea" },
        { "countryId": 54, "countryName": "Eritrea" },
        { "countryId": 55, "countryName": "Estonia" },
        { "countryId": 56, "countryName": "Eswatini" },
        { "countryId": 57, "countryName": "Ethiopia" },
        { "countryId": 58, "countryName": "Fiji" },
        { "countryId": 59, "countryName": "Finland" },
        { "countryId": 60, "countryName": "France" },
        { "countryId": 61, "countryName": "Gabon" },
        { "countryId": 62, "countryName": "Gambia" },
        { "countryId": 63, "countryName": "Georgia" },
        { "countryId": 64, "countryName": "Germany" },
        { "countryId": 65, "countryName": "Ghana" },
        { "countryId": 66, "countryName": "Greece" },
        { "countryId": 67, "countryName": "Grenada" },
        { "countryId": 68, "countryName": "Guatemala" },
        { "countryId": 69, "countryName": "Guinea" },
        { "countryId": 70, "countryName": "Guinea-Bissau" },
        { "countryId": 71, "countryName": "Guyana" },
        { "countryId": 72, "countryName": "Haiti" },
        { "countryId": 73, "countryName": "Honduras" },
        { "countryId": 74, "countryName": "Hungary" },
        { "countryId": 75, "countryName": "Iceland" },
        { "countryId": 76, "countryName": "India" },
        { "countryId": 77, "countryName": "Indonesia" },
        { "countryId": 78, "countryName": "Iran" },
        { "countryId": 79, "countryName": "Iraq" },
        { "countryId": 80, "countryName": "Ireland" },
        { "countryId": 81, "countryName": "Israel" },
        { "countryId": 82, "countryName": "Italy" },
        { "countryId": 83, "countryName": "Jamaica" },
        { "countryId": 84, "countryName": "Japan" },
        { "countryId": 85, "countryName": "Jordan" },
        { "countryId": 86, "countryName": "Kazakhstan" },
        { "countryId": 87, "countryName": "Kenya" },
        { "countryId": 88, "countryName": "Kiribati" },
        { "countryId": 89, "countryName": "Korea, North" },
        { "countryId": 90, "countryName": "Korea, South" },
        { "countryId": 91, "countryName": "Kuwait" },
        { "countryId": 92, "countryName": "Kyrgyzstan" },
        { "countryId": 93, "countryName": "Laos" },
        { "countryId": 94, "countryName": "Latvia" },
        { "countryId": 95, "countryName": "Lebanon" },
        { "countryId": 96, "countryName": "Lesotho" },
        { "countryId": 97, "countryName": "Liberia" },
        { "countryId": 98, "countryName": "Libya" },
        { "countryId": 99, "countryName": "Liechtenstein" },
        { "countryId": 100, "countryName": "Lithuania" },
        { "countryId": 101, "countryName": "Luxembourg" },
        { "countryId": 102, "countryName": "Madagascar" },
        { "countryId": 103, "countryName": "Malawi" },
        { "countryId": 104, "countryName": "Malaysia" },
        { "countryId": 105, "countryName": "Maldives" },
        { "countryId": 106, "countryName": "Mali" },
        { "countryId": 107, "countryName": "Malta" },
        { "countryId": 108, "countryName": "Marshall Islands" },
        { "countryId": 109, "countryName": "Mauritania" },
        { "countryId": 110, "countryName": "Mauritius" },
        { "countryId": 111, "countryName": "Mexico" },
        { "countryId": 112, "countryName": "Micronesia" },
        { "countryId": 113, "countryName": "Moldova" },
        { "countryId": 114, "countryName": "Monaco" },
        { "countryId": 115, "countryName": "Mongolia" },
        { "countryId": 116, "countryName": "Montenegro" },
        { "countryId": 117, "countryName": "Morocco" },
        { "countryId": 118, "countryName": "Mozambique" },
        { "countryId": 119, "countryName": "Myanmar" },
        { "countryId": 120, "countryName": "Namibia" },
        { "countryId": 121, "countryName": "Nauru" },
        { "countryId": 122, "countryName": "Nepal" },
        { "countryId": 123, "countryName": "Netherlands" },
        { "countryId": 124, "countryName": "New Zealand" },
        { "countryId": 125, "countryName": "Nicaragua" },
        { "countryId": 126, "countryName": "Niger" },
        { "countryId": 127, "countryName": "Nigeria" },
        { "countryId": 128, "countryName": "North Macedonia" },
        { "countryId": 129, "countryName": "Norway" },
        { "countryId": 130, "countryName": "Oman" },
        { "countryId": 131, "countryName": "Pakistan" },
        { "countryId": 132, "countryName": "Palau" },
        { "countryId": 133, "countryName": "Panama" },
        { "countryId": 134, "countryName": "Papua New Guinea" },
        { "countryId": 135, "countryName": "Paraguay" },
        { "countryId": 136, "countryName": "Peru" },
        { "countryId": 137, "countryName": "Philippines" },
        { "countryId": 138, "countryName": "Poland" },
        { "countryId": 139, "countryName": "Portugal" },
        { "countryId": 140, "countryName": "Qatar" },
        { "countryId": 141, "countryName": "Romania" },
        { "countryId": 142, "countryName": "Russia" },
        { "countryId": 143, "countryName": "Rwanda" },
        { "countryId": 144, "countryName": "Saint Kitts and Nevis" },
        { "countryId": 145, "countryName": "Saint Lucia" },
        { "countryId": 146, "countryName": "Saint Vincent and the Grenadines" },
        { "countryId": 147, "countryName": "Samoa" },
        { "countryId": 148, "countryName": "San Marino" },
        { "countryId": 149, "countryName": "Sao Tome and Principe" },
        { "countryId": 150, "countryName": "Saudi Arabia" },
        { "countryId": 151, "countryName": "Senegal" },
        { "countryId": 152, "countryName": "Serbia" },
        { "countryId": 153, "countryName": "Seychelles" },
        { "countryId": 154, "countryName": "Sierra Leone" },
        { "countryId": 155, "countryName": "Singapore" },
        { "countryId": 156, "countryName": "Slovakia" },
        { "countryId": 157, "countryName": "Slovenia" },
        { "countryId": 158, "countryName": "Solomon Islands" },
        { "countryId": 159, "countryName": "Somalia" },
        { "countryId": 160, "countryName": "South Africa" },
        { "countryId": 161, "countryName": "South Sudan" },
        { "countryId": 162, "countryName": "Spain" },
        { "countryId": 163, "countryName": "Sri Lanka" },
        { "countryId": 164, "countryName": "Sudan" },
        { "countryId": 165, "countryName": "Suriname" },
        { "countryId": 166, "countryName": "Sweden" },
        { "countryId": 167, "countryName": "Switzerland" },
        { "countryId": 168, "countryName": "Syria" },
        { "countryId": 169, "countryName": "Taiwan" },
        { "countryId": 170, "countryName": "Tajikistan" },
        { "countryId": 171, "countryName": "Tanzania" }
      ]
      )
    return (
        <div className="border rounded-md mb-5">
            <button
                className="w-full p-4 text-left bg-gray-800  
                           hover:bg-gray-900 text-white transition duration-300"
                onClick={props.toggleAccordion}
            >
                {props.title}
                <span className={`float-right transform ${props.isOpen ?
                    'rotate-180' : 'rotate-0'}  
                                 transition-transform duration-300`}>
                    &#9660;
                </span>
            </button>
            {props.isOpen && (
                <div className="p-4 bg-white">
                    {!props.country && !props.sector && props.data.map((data) => {
                        return (
                            <button key={data} className='bg-gray-100 text-black w-auto py-2 px-3 rounded-md font-medium w-[100px] me-3 mt-3'>
                                {data}
                            </button>
                        )
                    })}
                    {props.country && props.data.map((data) => {
                        return (
                            <button key={data} className='bg-gray-100 text-black w-auto py-2 px-3 rounded-md font-medium w-[100px] me-3 mt-3'>
                                {allCountries.filter(x => x.countryId === data)[0].countryName}
                            </button>
                        )
                    })}
                    {props.sector && props.data.map((data) => {
                        return (
                            <button key={data} className='bg-gray-100 text-black w-auto py-2 px-3 rounded-md font-medium w-[100px] me-3 mt-3'>
                                {allSectors.filter(x => x.sectorId === data)[0].sectorName}
                            </button>
                        )
                    })}
                </div>
            )}
        </div>
    );
}; 